#
# Copyright 2016 Pixar
#
# Licensed under the Apache License, Version 2.0 (the "Apache License")
# with the following modification; you may not use this file except in
# compliance with the Apache License and the following modification to it:
# Section 6. Trademarks. is deleted and replaced with:
#
# 6. Trademarks. This License does not grant permission to use the trade
#    names, trademarks, service marks, or product names of the Licensor
#    and its affiliates, except as required to comply with Section 4(c) of
#    the License and to reproduce the content of the NOTICE file.
#
# You may obtain a copy of the Apache License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Apache License with the above modification is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the Apache License for the specific
# language governing permissions and limitations under the Apache License.
#

clone_folder: c:\projects\USD

branches:
    only:
        - dev_appv

platform:
    - x64

configuration:
    - 14 2015 Win64

build_script:

    - mkdir c:\packages

    # TBB
    - cd c:\packages
    - mkdir tbb
    - cd tbb
    - appveyor DownloadFile https://www.threadingbuildingblocks.org/sites/default/files/software_releases/windows/tbb44_20160526oss_win_0.zip -FileName tbb.zip
    - 7z x tbb.zip
    - 

    # IlmBase
    - cd c:\packages
    - mkdir openexr
    - cd openexr
    - appveyor DownloadFile https://github.com/openexr/openexr/archive/v2.2.0.zip -FileName openexr.zip
    - 7z x openexr.zip
    - dir
    - cd c:\packages\openexr\openexr-2.2.0\IlmBase
    - dir
    - mkdir build
    - cd build
    - cmake -G "Visual Studio %Configuration%" \
            -DCMAKE_INSTALL_PREFIX="c:/packages/openexr" \
            ..
    - cmake --build . --target install --config Release


    # USD
    - cd c:\projects\USD
    - mkdir build
    - cd build
    - cmake --version
    - cmake -G "Visual Studio %Configuration%" \
            -D "PXR_BUILD_ALEMBIC_PLUGIN:bool=FALSE" \
            -D "PXR_BUILD_KATANA_PLUGIN:bool=FALSE" \
            -D "PXR_BUILD_MAYA_PLUGIN:bool=FALSE" \
            -D "PXR_BUILD_IMAGING:bool=FALSE" \
            -D "PXR_BUILD_TESTS:bool=FALSE" \
            -D "PYTHON_EXECUTABLE:filepath=c:/Python27-x64/python.exe" \
            -D "PYTHON_LIBRARY:string=c:/Python27-x64/libs\python27.lib" \
            -D "PYTHON_INCLUDE_DIR:string=c:/Python27-x64/include" \
            -D "BOOST_ROOT:string=c:/Libraries/boost_1_62_0" \
            -D "BOOST_LIBRARYDIR:string=c:/Libraries/boost_1_62_0/lib64-msvc-14.0" \
            -D "Boost_USE_STATIC_LIBS:INT=0" \
            -D "TBB_LIBRARY:string=c:/packages/tbb/tbb44_20160526oss/lib/intel64/vc14/" \
            -D "TBB_LIBRARIES:string=c:/packages/tbb/tbb44_20160526oss/lib/intel64/vc14/tbb.lib" \
            -D "TBB_INCLUDE_DIRS:string=c:/packages/tbb/tbb44_20160526oss/include" \
            -D "OPENEXR_LIBRARY_DIR:string=c:/packages/openexr" \
            -D "OPENEXR_INCLUDE_DIR:string=c:/packages/openexr/include" \
            -D "OPENEXR_Half_LIBRARY:string=c:/packages/openexr/lib/Half.lib" \
            ..
    - cmake --build . --config Release
