trigger:
- dev_az

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get -qq update;
      sudo pip install --upgrade pip
    displayName: 'Updating on Linux...'
  - script: |
      sudo apt-get install python-setuptools;
      sudo apt-get install libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev;
      sudo apt-get install python-pyside pyside-tools ;
      sudo pip install PyOpenGL ;
    displayName: 'Installing prereqs on Linux'
  - script: |
      sudo python build_scripts/build_usd.py --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
    displayName: 'Running build_usd.py'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer"      
    displayName: 'Set up Xcode'
  - script: |
      sudo pip install pyside2 ;
      sudo pip install PyOpenGL ;
    displayName: 'Installing dependencies on macOS'
  - script: |
      python build_scripts/build_usd.py -v --generator Xcode --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
    displayName: 'Running build_usd.py'

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  #- task: UsePythonVersion@0
  #  inputs:
  #    versionSpec: '2.7'
  #    architecture: 'x64'
  - script: |
      call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      call set PATH=C:/Python27amd64;C:/Python27amd64/Scripts;%PATH%
      call python --version
      call python -m pip install --upgrade pip
      call python -m pip install pyside
      call python -m pip install PyOpenGL
      call python build_scripts/build_usd.py -v --build-args USD,"-DPYTHON_EXECUTABLE:FILEPATH=C:/Python27amd64/python.exe" --build %HOME%/USDgen/build --src %HOME%/USDgen/src %HOME%/USDinst
    displayName: 'Running build_usd.py'
