trigger:
- dev_az

pool:
  vmImage: 'Ubuntu-16.04'

steps:
    - script: |
        sudo apt-get -qq update ;
        sudo pip install --upgrade pip
      displayName: 'Updating...'
    - script: |
        sudo apt-get install libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev;
        sudo apt-get install python-pyside pyside-tools ;
        sudo pip install PyOpenGL ;
      displayName: 'Installing prereqs'
    - script: |
        python build_scripts/build_usd.py -v --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
      displayName: 'Running build_usd.py'
