trigger:
- dev_az

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    python build_scripts/build_usd.py -v --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
  displayName: 'Running build_usd.py'
