trigger:
- dev_az

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get -qq update;
      sudo pip install --upgrade pip
    displayName: 'Updating on Linux...'
  - script: |
      sudo apt-get install python-setuptools;
      sudo apt-get install libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev;
      sudo apt-get install python-pyside pyside-tools ;
      sudo pip install PyOpenGL ;
    displayName: 'Installing prereqs on Linux'
  - script: |
      sudo python build_scripts/build_usd.py --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
    displayName: 'Running build_usd.py'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      sudo pip install pyside2 ;
      sudo pip install PyOpenGL ;
    displayName: 'Installing dependencies on macOS'
  - script: |
      python build_scripts/build_usd.py -v --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst
    displayName: 'Running build_usd.py'

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: |
      python -m pip install --upgrade pip
      python -m pip install pyside2
      python -m pip install PyOpenGL
    displayName: 'Installing dependencies on Windows'
  - script: |
      python build_scripts/build_usd.py -v --build %HOME%/USDgen/build --src %HOME%/USDgen/src %HOME%/USDinst
    displayName: 'Running build_usd.py'
